name: Deploy completo (excavatrack)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:

  # ============================================================
  # BACK-END - LARAVEL
  # ============================================================
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Deploy Backend Laravel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          local-dir: ./back-end/
          server-dir: /adminexpansao.hrsistememas.com.br/back-end/

          exclude: |
            **/.git/**
            **/.github/**
            **/.env
            **/.env.example
            **/node_modules/**
            **/storage/logs/**
            **/storage/framework/cache/**
            **/storage/framework/sessions/**
            **/storage/framework/views/**


  # ============================================================
  # FRONT-END - REACT / VITE
  # ============================================================
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: front-end/package-lock.json

      - name: Instalar dependências
        working-directory: ./front-end
        run: npm ci

      - name: Build Front-end
        working-directory: ./front-end
        run: npm run build

      - name: Deploy Front-end
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          local-dir: ./front-end/dist/
          server-dir: /adminexpansao.hrsistememas.com.br/front-end

          exclude: |
            **/.git/**
            **/.github/**